Feat/set comment model
urlabs/blog pull request #2
Opened 2023-02-06 16:41 UTC by ricardovaltierra

The following changes were made:

2023-02-06 18:35 UTC, 3zcurdia requested changes

2023-02-06 19:37 UTC, ricardovaltierra commented on main.rb
> +      render json: comment_params , status: :ok
Changing it 👍🏾️. I made it this way in order to pass the test as it was set [here](https://github.com/urlabs/blog/blob/791b19ac11e6e3d651ffae47ca971535f7c62c6f/main.rb#L215)

Thanks for your patience. I was finishing my meal.

2023-02-06 22:03 UTC, ricardovaltierra commented on main.rb
> +  def destroy; end
Ok 👍🏾️

2023-02-06 22:14 UTC, ricardovaltierra commented on main.rb
> +  end
Still to push modify the model to create comments within comments

2023-02-06 22:14 UTC, ricardovaltierra commented
Still to push modify the model to set comments within comments

2023-02-07 15:44 UTC, 3zcurdia commented on main.rb
> +  add_index "posts", ["comments_count"], name: "index_posts_on_comments_count", using: :btree
why did you add an index to a counter?

2023-02-07 15:44 UTC, 3zcurdia commented on main.rb
> +    puts "COMMENTS_COUNT BEFORE REQUEST: #{before_coments_count}"
this fine while you are working, but is unacceptable on the commit specially when you have tests

2023-02-07 15:44 UTC, 3zcurdia commented on main.rb
> +  belongs_to :post, counter_cache: true
👍

2023-02-07 15:46 UTC, 3zcurdia commented on main.rb
> +    @post.with_lock do
why do you need the lock, when you are using counter cache?

2023-02-07 15:49 UTC, ricardovaltierra commented on main.rb
> +  add_index "posts", ["comments_count"], name: "index_posts_on_comments_count", using: :btree
Recommendation from ChatGPT after adding a default: 0. Should I remove it?

2023-02-07 15:49 UTC, ricardovaltierra commented on main.rb
> +    puts "COMMENTS_COUNT BEFORE REQUEST: #{before_coments_count}"
Removing it

2023-02-07 16:33 UTC, ricardovaltierra commented on main.rb
> +    @post.with_lock do
Thought it was required, as another security measure. Removing it.

2023-02-07 17:45 UTC, 3zcurdia commented on main.rb
> +  add_index "posts", ["comments_count"], name: "index_posts_on_comments_count", using: :btree
Yes, sometimes AI generated code will include hallucinations, this the perfect example. Even when the syntax and grammar are correct, this is not required because none expect to make queries over counters. 

Remember that indexes exists to improve performance in queries.

2023-02-07 17:55 UTC, 3zcurdia commented on main.rb
> +  add_index "posts", ["comments_count"], name: "index_posts_on_comments_count", using: :btree
Also I strongly recommend you, do not use AI to generate code, specially with your experience level.

2023-02-07 18:02 UTC, ricardovaltierra commented on main.rb
> +  add_index "posts", ["comments_count"], name: "index_posts_on_comments_count", using: :btree
Ok, removing it

2023-02-16 22:42 UTC, 3zcurdia commented on main.rb
> +      render json: { comment: @comment, success: false, message: "Comment could not be saved. Errors: #{@comment.errors}" }, status: :unprocessable_entity
```suggestion
      render json: { errors: @comment.errors }, status: :unprocessable_entity
```

2023-02-16 23:41 UTC, closed without merging